site_name: Epure Docs
site_url: https://epurelib.github.io/epure-docs

# Repository
repo_name: nagvalhm/epure
repo_url: https://github.com/nagvalhm/epure

theme:
  name: material
  custom_dir: overrides

extra:
  version:
    provider: mike