site_name: Epure
site_url: https://epurelib.github.io/epure-docs


# Repository
repo_name: nagvalhm/epure
repo_url: https://github.com/nagvalhm/epure

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.select
    - navigation.tabs
    - navigation.sections
  logo: assets/img/logo.svg
  # logo: assets/images/favicon.png
  palette:
    primary: white

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Welcome to Epure: index.md
  # - Features: features.md
  - Learn: 
    - ./learn/learn.md
    
    - Eset and Elist: ./learn/elist_eset.md
    - Join: ./learn/joins.md
    - Domain and Model: ./learn/domain_model.md
    - More about IniFile parser: ./learn/ini_parser.md
    - Supported DataBases: ./learn/supported_db.md
    - Epure essentials ⭐:
      - "@escript decorator and magic methods 🔮": ./learn/epure_essentials/escript_decorator.md
      - Supported ColumnProxy methods with @escript decorator: ./learn/epure_essentials/column_proxy_methods.md
      - "@epure() decorator and overriding storing for @epure": ./learn/epure_essentials/epure_cls.md
      - Epure supported types: ./learn/epure_essentials/supported_types.md
      - Reading from resource with `.read()`: ./learn/epure_essentials/epure_read.md
    - Serialization and Deserialization to JSON and Dict ♻️: 
      - Serialization with to_dict and to_json: ./learn/serialization_deserialization/serialization.md
      - Deserialization with from_dict and from_json: ./learn/serialization_deserialization/deserialization.md
  - Help: help.md
  - Contribute: contribute.md
  - Release Notes: release_notes.md

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css